CREATE TABLE roles (name VARCHAR(16) PRIMARY KEY CHECK (name IN ('CUSTOMER','ADMIN')));
INSERT INTO roles VALUES ('CUSTOMER'), ('ADMIN');
CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login VARCHAR(32) NOT NULL UNIQUE CHECK (login ~ '^[a-z0-9_]{3,32}$'),
    password_hash VARCHAR(60) NOT NULL CHECK (password_hash LIKE '$2a$%'),
    role VARCHAR(16) NOT NULL DEFAULT 'CUSTOMER' REFERENCES roles(name),
    balance NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (balance >= 0 AND balance <= 999999999999.99),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seed_key VARCHAR(64) UNIQUE,
    title VARCHAR(120) NOT NULL CHECK (length(trim(title)) > 0),
    genre VARCHAR(40) NOT NULL CHECK (length(trim(genre)) > 0),
    price NUMERIC(14,2) NOT NULL CHECK (price >= 0 AND price <= 999999999999.99),
    image VARCHAR(160) NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE cart_items (
    user_id BIGINT NOT NULL REFERENCES users(id),
    game_id BIGINT NOT NULL REFERENCES games(id),
    PRIMARY KEY(user_id, game_id)
);
CREATE TABLE orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    operation_id UUID NOT NULL UNIQUE,
    total NUMERIC(14,2) NOT NULL CHECK (total >= 0 AND total <= 999999999999.99),
    currency CHAR(3) NOT NULL DEFAULT 'KZT' CHECK (currency = 'KZT'),
    status VARCHAR(16) NOT NULL CHECK (status IN ('PENDING','PAID','DECLINED','IMPORTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source VARCHAR(16) NOT NULL DEFAULT 'CHECKOUT' CHECK (source IN ('CHECKOUT','LEGACY')),
    UNIQUE (id,user_id)
);
CREATE INDEX orders_user_date ON orders(user_id, created_at DESC);
CREATE TABLE order_items (
    order_id BIGINT NOT NULL REFERENCES orders(id),
    game_id BIGINT NOT NULL REFERENCES games(id),
    title VARCHAR(120) NOT NULL,
    price NUMERIC(14,2) NOT NULL CHECK (price >= 0 AND price <= 999999999999.99),
    PRIMARY KEY (order_id,game_id)
);
CREATE TABLE payment_attempts (
    operation_id UUID PRIMARY KEY,
    request_key VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    order_id BIGINT UNIQUE,
    amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0 AND amount <= 999999999999.99),
    status VARCHAR(16) NOT NULL CHECK (status IN ('SUCCEEDED','DECLINED')),
    balance_after NUMERIC(14,2) NOT NULL CHECK (balance_after >= 0 AND balance_after <= 999999999999.99),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (order_id,user_id) REFERENCES orders(id,user_id)
);
CREATE TABLE library (
    user_id BIGINT NOT NULL REFERENCES users(id),
    game_id BIGINT NOT NULL REFERENCES games(id),
    order_id BIGINT NOT NULL,
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id,game_id),
    FOREIGN KEY (order_id,user_id) REFERENCES orders(id,user_id),
    FOREIGN KEY (order_id,game_id) REFERENCES order_items(order_id,game_id)
);
CREATE TABLE balance_operations (
    operation_id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0 AND amount <= 100000),
    balance_after NUMERIC(14,2) NOT NULL CHECK (balance_after >= 0 AND balance_after <= 999999999999.99),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE legacy_imports (
    fingerprint CHAR(64) PRIMARY KEY,
    old_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL REFERENCES users(id),
    imported_rows INTEGER NOT NULL CHECK (imported_rows >= 0),
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
